# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

# NOTE: This workflow is maintained in the https://github.com/helmhub-io/support repository
name: '[Support] Comments based card movements'
on:
  issue_comment:
    types:
      - created
permissions:
  contents: read
  pull-requests: write
  issues: write
#Â Avoid concurrency over the same issue
concurrency:
  group: card-movement-${{ github.event.issue.number }}
jobs:
  request-review:
    name: Request review
    if: ${{ github.repository_owner == 'helmhub-io' }}
    uses: helmhub-io/support/.github/workflows/item-comments-request-review.yml@main
    secrets: inherit